{NA <type 'exceptions.AssertionError'> AssertionError(5,)
 Traceback (most recent call last):
  File "regression-tests/assert_with_arg.py", line 5, in foo
    assert x > 10, x

Locals: {'x': 5}
}
{AssertionError: Set local var 'x' to NA | regression-tests/assert_with_arg.py foo:5}
{NA <type 'exceptions.AssertionError'> AssertionError(5,)
 Traceback (most recent call last):
  File "regression-tests/assert_with_arg.py", line 5, in foo
    assert x > 10, x

Locals: {'x': 5}
}
{AssertionError: Set local var 'x' to NA | regression-tests/assert_with_arg.py foo:5}
{NA <type 'exceptions.AssertionError'> AssertionError(5,)
 Traceback (most recent call last):
  File "regression-tests/assert_with_arg.py", line 5, in foo
    assert x > 10, x

Locals: {'x': 5}
}
{AssertionError: Set local var 'x' to NA | regression-tests/assert_with_arg.py foo:5}
