{NA <type 'exceptions.ValueError'> "invalid literal for int() with base 10: 'bad'"
 Traceback (most recent call last):
  File "regression-tests/gen_func.py", line 9, in foo
    y = 20 * int(x)

Locals: {'y': 40, 'x': 'bad', 'l': ['1', '2', 'bad', '3', 'bad2', 'bad3', 'bad4', '4']}
}
{binary_op(*,NA) | regression-tests/gen_func.py foo:9}
{gen_iternext() yielded NA | regression-tests/gen_func.py <module>:13}
{NA <type 'exceptions.ValueError'> "invalid literal for int() with base 10: 'bad2'"
 Traceback (most recent call last):
  File "regression-tests/gen_func.py", line 9, in foo
    y = 20 * int(x)

Locals: {'y': 60, 'x': 'bad2', 'l': ['1', '2', 'bad', '3', 'bad2', 'bad3', 'bad4', '4']}
}
{binary_op(*,NA) | regression-tests/gen_func.py foo:9}
{gen_iternext() yielded NA | regression-tests/gen_func.py <module>:13}
{PyObject_SetItem(value=NA) | regression-tests/gen_func.py foo:9}
{NA <type 'exceptions.ValueError'> "invalid literal for int() with base 10: 'bad3'"
 Traceback (most recent call last):
  File "regression-tests/gen_func.py", line 9, in foo
    y = 20 * int(x)

Locals: {'y': 60, 'x': 'bad3', 'l': ['1', '2', 'bad', '3', 'bad2', 'bad3', 'bad4', '4']}
}
{PyObject_SetItem(value=NA) | regression-tests/gen_func.py foo:9}
{binary_op(*,NA) | regression-tests/gen_func.py foo:9}
{gen_iternext() yielded NA | regression-tests/gen_func.py <module>:13}
{PyObject_SetItem(value=NA) | regression-tests/gen_func.py foo:9}
{NA <type 'exceptions.ValueError'> "invalid literal for int() with base 10: 'bad4'"
 Traceback (most recent call last):
  File "regression-tests/gen_func.py", line 9, in foo
    y = 20 * int(x)

Locals: {'y': 60, 'x': 'bad4', 'l': ['1', '2', 'bad', '3', 'bad2', 'bad3', 'bad4', '4']}
}
{PyObject_SetItem(value=NA) | regression-tests/gen_func.py foo:9}
{binary_op(*,NA) | regression-tests/gen_func.py foo:9}
{gen_iternext() yielded NA | regression-tests/gen_func.py <module>:13}
